import type { AppProps } from "next/app";
import Head from "next/head";
import { ToastContainer } from "react-toastify";
import { AuthProvider } from "../hooks/useAuth";
import "../styles/globals.css";
import "react-toastify/dist/ReactToastify.css";
import "react-loader-spinner/dist/loader/css/react-spinner-loader.css";

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Github Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AuthProvider>
        <ToastContainer position="top-right" />
        <Component {...pageProps} />
      </AuthProvider>
    </>
  );
}

export default MyApp;
